### ISSUE TITLE
undefined method `author' for #<RSS::RDF::Item:0x5b...>>

### ISSUE THREAD

**Issue by ldrolez** [logstash-plugins/logstash-input-rss#22]
With the latest plugin, master branch, I still get those errors. 
I think a few `if !item.author.nil?` are missing in handle_rss_response and handle_response.

**Comment by ldrolez** [comment]
same problem with pubDate tag not always present in feeds...

**Comment by matthew-williams** [comment]
I get the following error after logstash initializes.

> [2018-01-05T08:52:42,046][ERROR][logstash.inputs.rss      ] Uknown error while parsing the feed {:url=>"https://static.nvd.nist.gov/feeds/xml/cve/misc/nvd-rss-analyzed.xml", :exception=>#<NoMethodError: undefined method `author' for #<RSS::RDF::Item:0x5c6798d5>>}

**Comment by matthew-williams** [comment]
[tail_logstash-plain.log](https://github.com/logstash-plugins/logstash-input-rss/files/1607138/tail_logstash-plain.log)

**Comment by ldrolez** [comment]
Yes, I confirm this bug has still not been fixed...

**Comment by fabionoth** [comment]
`:exception=>#<RSS::NotAvailableValueError: value <> of tag <pubDate> is not available.>`
here is my log.

**Comment by Whysmerhill** [comment]
This issue is still not fixed.
Error log I got : 

`[ERROR][logstash.inputs.rss      ][rss][b7f237bfd64fe173869e21fe2a6e04488f2f091d0d887f5d66016307c98d8825] Uknown error while parsing the feed {:url=>"https://nvd.nist.gov/feeds/xml/cve/misc/nvd-rss.xml", :exception=>#<NoMethodError: undefined method `author' for #<RSS::RDF::Item:0x9e3a8fb>>}`
